name: Orange Sun Labs beta
favicon: null
layout_spectrum: 0.8467480828985572
typography_spectrum: 0.7532018185593188
title: Science from Silence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2321854722686112
  lightness: 0.3717779889702797
  saturation: 0.9892994079273194
  rhythmicContrast: 0.9708693299908191
purpose: []
